# Generated by Django 2.1.1 on 2018-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaHBD',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numHijos',
            field=models.IntegerField(default=0),
        ),
    ]
